apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-node-app
  name: simple-node-app
spec:
  selector:
    app: simple-node-app
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080